Loading required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import SoCCo as sc

Setting initial conditions

In [2]:
co2_ts=np.linspace(290, 300, 4)
popTotal=7130010000 # Wolfram: QuantityMagnitude[CountryData["World", "Population"]]
popN=sc.popIntoNgroups(popTotal,nGroups=10)
pcE_ts=sc.randomNormalF(5.049, 0.5, 10)
pcE_ts=np.atleast_2d(pcE_ts).transpose()
tData_ts=np.array([0,0.1,0.2,0.1]) # temperature
eff=sc.efficacyF(10)
pbc=sc.perceivedBehavioralControlF(10)
percepWindowSize=3
riskSens=1.0

In [3]:
pcE_ts,tData_ts, co2_ts=sc.iterateNsteps(pcE_ts,tData_ts, co2_ts, 5, eff, pbc,popN,percepWindowSize,riskSens)

In [4]:
pcE_ts

array([[ 5.47901475,  5.27970901,  5.18831243,  5.16573536,  5.18665424,
         5.23776395],
       [ 5.28156487,  5.20665313,  5.22384196,  5.28987954,  5.37941262,
         5.48132019],
       [ 4.53098968,  4.87583236,  5.0836753 ,  5.24386777,  5.38733169,
         5.52343625],
       [ 4.40724885,  4.42564082,  4.44374383,  4.463057  ,  4.48426474,
         4.50802769],
       [ 4.54460762,  4.7054713 ,  4.82601752,  4.93196001,  5.03301363,
         5.13364505],
       [ 5.42192589,  5.21091905,  5.16958209,  5.20026138,  5.26580204,
         5.35127236],
       [ 5.10168219,  5.33246296,  5.36772102,  5.44543775,  5.55296214,
         5.67027107],
       [ 5.6346966 ,  5.28054593,  5.38443676,  5.46212603,  5.57438206,
         5.69290442],
       [ 4.60491933,  4.80341863,  4.92578119,  5.02302682,  5.11242295,
         5.20232639],
       [ 5.23029835,  5.16434597,  5.13016742,  5.13240545,  5.16303744,
         5.21661561]])

In [5]:
tData_ts

array([ 0.        ,  0.1       ,  0.2       ,  0.1       ,  0.19980657,
        0.36805883,  0.62308532,  0.97970028,  1.4498099 ])

In [6]:
co2_ts

array([ 290.        ,  293.33333333,  296.66666667,  300.        ,
        322.97013364,  346.14960927,  369.6097776 ,  393.42694637,
        417.64532137])